---
abstract: 'TT2 plugin to format numeric values as binary octets'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Octets
no_index:
  directory:
    - t
    - inc
requires:
  Template: 0
  perl: 5.008009
resources:
  bugtracker: https://github.com/Wu-Wu/Template-Plugin-Octets/issues
  repository: https://github.com/Wu-Wu/Template-Plugin-Octets
version: 0.16
